# deployment.yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: pyremotedebug
    app.kubernetes.io/name: pyremotedebug
  name: pyremotedebug
  namespace: default
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: pyremotedebug
      app.kubernetes.io/name: pyremotedebug
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: pyremotedebug
        app.kubernetes.io/name: pyremotedebug
    spec:
      containers:
      - image: quay.io/omrikiei/pyremotedebug:latest
        imagePullPolicy: Always
        name: pyremotedebug
        ports:
        - containerPort: 8000
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: PORT
          value: "8000"
        - name: REMOTE_DEBUG_HOST
          value: "dbgsvc:4321"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
